name: periscope test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Print environment
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies on unx
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          g++ --version
          
      - name: Install dependencies on osx
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install llvm libomp
          clang++ --version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools --upgrade
          pip install -r requirements.txt

      - name: Build periscope back-end
        run: python setup.py build_ext --inplace

      - name: Download test assets
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: dengwirda/periscope
          file: mesh_w_elev_cvt_7.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download test assets
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: dengwirda/periscope
          file: mesh_disk_2.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Unpack test assets
        run: unzip "*.zip"

      - name: Run periscope testcase 1
        run: |
          python ICs/wtc.py \
          --mesh-file="mesh_w_elev_cvt_7.nc" \
          --init-file="wtc2_cvt_7.nc" \
          --radius=6371220. \
          --test-case=2
          python swe.py \
          --mesh-file="wtc2_cvt_7.nc" \
          --numthread=2 \
          --num-steps=576 --time-step=300.0 \
          --save-freq=288 --stat-freq=288 \
          --integrate="RK32-FB"
          
      - name: Run periscope testcase 2
        run: |
          python3 ICs/jet.py \
          --mesh-file="mesh_w_elev_cvt_7.nc" \
          --init-file="bjet_cvt_7.nc" \
          --radius=6371220. \
          --with-pert=TRUE
          python3 swe.py \
          --mesh-file="bjet_cvt_7.nc" \
          --numthread=2 \
          --num-steps=640 --time-step=135.0 \
          --save-freq=640 --stat-freq=320 \
          --integrate="RK22-FB"
          
      - name: Run periscope testcase 3
        run: |
          python3 ICs/vtx.py \
          --mesh-file="mesh_disk_2.nc" \
          --init-file="merger_2.nc" \
          --test-case=1
          python3 swe.py \
          --mesh-file="merger_2.nc" \
          --numthread=2 \
          --num-steps=500 --time-step=0.002 \
          --save-freq=250 --stat-freq=250
          
      - name: Run periscope testcase 4
        run: |
          python3 ICs/obc.py \
          --mesh-file="mesh_disk_2.nc" \
          --init-file="wake_2.nc" \
          --radius=50000. \
          --test-case=1
          python3 swe.py \
          --mesh-file="wake_2.nc" \
          --forc-file="frc_wake_2.nc" \
          --num-steps=864 --time-step=0.125 \
          --save-freq=288 --stat-freq=288 \
          --hh-scheme="upwind" \
          --wetdry-h0=1.E-03 \
          --loglaw-z0=0.0010 --loglaw-lo=0.0025 --loglaw-hi=1. \
          --uu-visc-2=1.E+02 --uu-visc-4=1.E+11 \
          --hh-diff-2=1.E+02 --hh-diff-4=1.E+11 \
          --leith-chi=0.3875 --leith-max=1.E+04
